apiVersion: v1
kind: Service
metadata:
  name: tetris-service
  namespace: tetris-game
spec:
  selector:
    app: tetris
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
