apiVersion: v1
kind: Service
metadata:
  name: tetris-service
  namespace: tetris
  labels:
    app: tetris
spec:
  selector:
    app: tetris
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP  # Changed from NodePort to ClusterIP for ALB
